### ISSUE TITLE
configure: line 3335: syntax error near unexpected token `LZ4,'

### ISSUE THREAD

**Issue by cmdj13** [switchbrew/switch-tools#1]
After installing msys (standalone, not the one from devkitPro), devkitPro, devkitA64 and libnx on a Windows 10 Pro PC I wanted to build switch-tools so I ran `autogen.sh` and then `configure`.

configure gives me this output:

> $ ./configure
> checking for a BSD-compatible install... /bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... /bin/mkdir -p
> checking for gawk... gawk
> checking whether make sets $(MAKE)... yes
> checking build system type... i686-pc-mingw32
> checking host system type... i686-pc-mingw32
> checking for gcc... gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.exe
> checking for suffix of executables... .exe
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking for style of include used by make... GNU
> checking dependency style of gcc... gcc3
> ./configure: line 3335: syntax error near unexpected token \`LZ4,'
> ./configure: line 3335: \`PKG_CHECK_MODULES(LZ4,'

To make sure this isn't a Windows error, I also tried building switch-tools on a Ubuntu 17.10 x64 virtual machine, but without installing libnx. Here the same error occurred.

I'm not really familiar with make, configure and the rest so I can not say what exactly the syntax error is or why it happens.

**Comment by yellows8** [comment]
pinging @WinterMute

**Comment by WinterMute** [comment]
Build and install liblz4 from https://github.com/lz4/lz4

**Comment by cmdj13** [comment]
Installing liblz4 did not fix this syntax error, neither on WIndows nor on Ubuntu.
What I meant by installing devkitPro is that I ran the devkitPro installer (the script on Ubuntu) and installed devkitARM, just to be sure where to copy the devkitA64 folder.

**Comment by kapeas** [comment]
Hello,
Got the same issue here whith last version of LZ4 (from github link repo WinterMute said) installed on Ubuntu 17.
Line failing at configure is (in my case) 3536. Message is the same.

> checking dependency style of gcc... gcc3
> ./configure: line 3536: syntax error near unexpected token `LZ4,'
> ./configure: line 3536: `PKG_CHECK_MODULES(LZ4,'


Anything I can provide for further investigation?
Thanks for your effort.
Kapeas.

**Comment by WinterMute** [comment]
`sudo apt-get install pkg-config`

**Comment by kapeas** [comment]
Thanks for the help. It worked :) Will keep testing the rest of the tools

**Comment by Hexexpeck** [comment]
I'm getting the same error, I tried running `sudo apt-get install pkg-config` and I even built liblz4 from source, but I'm still getting this syntax error.
