### ISSUE TITLE
[romfs building] skip dotfiles

### ISSUE THREAD

**Issue by TurtleP** [switchbrew/switch-tools#17]
It's an unlikely scenario to occur (for the most part), but if one's assets for the romfs are on GitHub, it will also pull in the `.git` and `.gitignore` directory/files. This winds up with an nro that can be unexpectedly bloated.

![](https://i.imgur.com/zx9RP4V.png)

Love Potion for example has this problem because game assets are typically on GitHub and pulling those in as a romfs directory when building will pull those aforementioned directories and files in, resulting in.. well.. a giant nro file which should only be a few megabytes. This should also be applied to 3dsxtool when building the romfs, but I'll open a separate issue for that on the proper repository.

**Comment by yellows8** [comment]
Are you setting ROMFS to another repo's root dir?

**Comment by AnalogMan151** [comment]
Definitely helps on Macs!

**Comment by TurtleP** [comment]
Closing as this is no longer an issue for what I am doing. If it's applicable to anyone else, I guess it could be reopened otherwise.
