### ISSUE TITLE
Icon can't be found

### ISSUE THREAD

**Issue by godreborn** [switchbrew/switch-tools#46]
I think this is with libnx, but I was trying to compile sm64nx, and it keeps being unable to find the icon.  

![image](https://github.com/switchbrew/switch-tools/assets/13548481/e58d3b87-3173-4485-a3a8-14e63e838ead)

I tried to get this built all day, and nothing.  this is what it looks like in the makefile.  as a non-dev, I don't know if this is even correct, but all commits seem to have the same information in the make file.  I noticed that it's called default_icon.jpg in libnx, but here it's called icon.jpg.  is that the reason?  I tried changing the name, and I got the same error.

**Comment by yellows8** [comment]
That's an issue with sm64nx, ask in that repo. (icon.jpg appears to be missing, also doesn't have fallback for using default-icon)
