### ISSUE TITLE
[Help] How to build switch-tools

### ISSUE THREAD

**Issue by enriicsolaa** [switchbrew/switch-tools#48]
I'm just starting out in the world of creating homebrews for the Nintendo Switch, and I've seen a lot of tutorials using tools from this pack, but I can't find a way to make a build. I've used chatGPT but no solution works for me. Can anyone help me? Thanks.

**Comment by WinterMute** [comment]
switch-tools are distributed in binary form via (dkp-)pacman. See https://devkitpro.org/wiki/Getting_Started

Unless you're contributing there is no need to make a build yourself and we discourage end users from doing this. unfortunately most tutorials you'll find are written without the assistance of devkitPro staff and published in places we can't access for updating when mistakes are made or things just need updating for latest tools and libraries. For this reason we cannot provide support for modified toolchain installs.
