### ISSUE TITLE
Broken Homebrew

### ISSUE THREAD

**Issue by admiralspeedy** [switchbrew/switch-tools#51]
I noticed today that if I build nx-ovlloader with switch-tools 13.X the resulting build does not work on Atmosphere 1.7.1 or older, only on the current pre-release 1.8.0 version.

It does not produce any errors, I simply cannot open the Tesla menu. If I downgrade switch-tools to 12.1.0, the resulting build works on 1.7.1.

**Comment by SciresM** [comment]
I don't think that's a bug, that seems correct. Nintendo made a breaking change in NPDM representation.

**Comment by SciresM** [comment]
I would (obviously) just recommend using Atmosphere 1.8.0.

**Comment by admiralspeedy** [comment]
I am now, however I still think it's a bug.

My Switch is on 18.1.0 so I should be able to build for AMS 1.7.1. If the intention is to drop support for older versions of HOS in these libraries then I think it should probably be noted somewhere.

**Comment by SciresM** [comment]
Atmosphere 1.8.0 supports older versions of HOS. This was, as I said, a breaking change in NPDMs. 

If you want your homebrew to run on atmosphere 1.7.1, change "force_debug":"true" in your sysmodule's configuration json to "force_debug_prod":"true", and it will work.

**Comment by SciresM** [comment]
This is decidedly not a bug, and you can always edit your configuration to make your homebrew work with older versions of atmosphere -- it will just then not work properly with atmosphere 1.8.0.

**Comment by SciresM** [comment]
(Note that force_debug/force_debug_prod/allow_debug are all mutually exclusive. "force_debug" must be false in configurations built with newer tools for the homebrew to function on atmosphere 1.7.1, and if you want the functionality it grants you set force_debug as true.)

**Comment by admiralspeedy** [comment]
> This is decidedly not a bug, and you can always edit your configuration to make your homebrew work with older versions of atmosphere -- it will just then not work properly with atmosphere 1.8.0.

I understand, but that's not documented anywhere at all. I quite literally spent all evening figuring it out myself tonight because there is no mention that there was breaking changes.

I mean yah, the answer is to just go to 1.8.0 but I originally was holding off because it's still pre-release.

**Comment by SciresM** [comment]
These are details that are only relevant to the developers of system modules, and system modules already need to take care to stay synchronized with new atmosphere versions. This is far from the first breaking change we've had, where recompiles were needed. Nintendo frequently changes stuff like this, and if you are making a system module (as opposed to a normal userland homebrew), it's just part of how the ecosystem works.

I think this issue should be closed given a) it's not a bug, b) there is a workaround which allows you to use the newer tools to build something compatible with older atmosphere revisions anyway.
